DROP TABLE Books;
DROP TABLE BookEvents;

CREATE TABLE Books (
  BookId UNIQUEIDENTIFIER PRIMARY KEY,
  Title NVARCHAR(800) NOT NULL,
  Owner NVARCHAR(800) NOT NULL,
  CreatedAt DATETIME NOT NULL,
  UpdatedAt DATETIME,
  DeletedAt DATETIME,
  IsDeleted BIT DEFAULT(0)
);

CREATE TABLE BookEvents (
  BookEventId UNIQUEIDENTIFIER PRIMARY KEY,
  BookId UNIQUEIDENTIFIER NOT NULL,
  EventType TINYINT NOT NULL,
  Timestamp DATETIME NOT NULL

	CONSTRAINT FK_BookEvents_Books
	FOREIGN KEY (BookId)
	REFERENCES Books(BookId)
);

